ALL: CrunchMain

FFLAGS  = -w 

SOURCEF = \
          crunchtype_OS.F90\
          params_OS.F90\
          strings_OS.F90\
          io_OS.F90\
          concentration_OS.F90\
          mineral_OS.F90\
          transport_OS.F90\
          medium_OS.F90\
          modflowModule_OS.F90\
          ReadFlow_OS.F90\
          RunTime_OS.F90\
          solver_OS.F90\
          temperature_OS.F90\
          flow_OS.F90\
          crunch_interface_OS.F90\
          CrunchFunctions_OS.F90\
          isotope_OS.F90\
          NanoCrystal_OS.F90\
          CrunchTopeDriver_OS.F90\
          CrunchTope_OS.F90\
          AffinityNumerical_OS.F90\
          AllocateALL_OS.F90\
          AllocateOS3D_OS.F90\
          AllocateGasesGimrt_OS.F90\
          AllocateGasesOS3D_OS.F90\
          AllocateGIMRT_OS.F90\
          AqueousFluxInitialize_OS.F90\
          AqueousFluxWrite_OS.F90\
          AqueousToBulkConvert_OS.F90\
          AssembleLocal_OS.F90\
          AssembleGlobal_OS.F90\
          AverageRo_OS.F90\
          bd_diffuse_OS.F90\
          bdcalc_OS.F90\
          bdexchange_OS.F90\
          bdgas_OS.F90\
          bdrecalc_OS.F90\
          bdsurf_OS.F90\
          breakfind_OS.F90\
          BreakFindPlusCount_OS.F90\
          BreakthroughInitialize_OS.F90\
          BreakthroughWrite_OS.F90\
          CalciteBulkStoichiometry_OS.F90\
          CalciteStoichiometry_OS.F90\
          CalciteStoichiometryBoundary_OS.F90\
          CalculateDHAD_OS.F90\
          CalculateTortuosity_OS.F90\
          coeff_OS.F90\
          coeff_D_OS.F90\
          coeffCylinder_OS.F90\
          coeffCylinder_D_OS.F90\
          coeffCylinderNUFT_OS.F90\
          coeffDiffuse_OS.F90\
          coeffNuft_OS.F90\
          coeffSphericalNew_OS.F90\
          coeffSphericalNew_d_OS.F90\
          convan_OS.F90\
          CourantStep_OS.F90\
          CourantStepAlt_OS.F90\
          CPUdefinition_OS.F90\
          CrunchPETScFinalizeSolver_OS.F90\
          CrunchPETScInitializeChemistry_OS.F90\
          CrunchPETScInitializeDiffusion_OS.F90\
          CrunchPETScInitializePressure_OS.F90\
          CrunchPETScTolerances_OS.F90\
          database_OS.F90\
          decay_OS.F90\
          decbt90_OS.F90\
          density_OS.F90\
          dispersivity_OS.F90\
          duan_OS.F90\
          equilib_co2_OS.F90\
          erosion_OS.F90\
          ex_activity_OS.F90\
          exactivity_init_OS.F90\
          exchange_OS.F90\
          exchange_init_OS.F90\
          ExchangeConcentration_OS.F90\
          find_condition_OS.F90\
          find_firststring_OS.F90\
          find_string_OS.F90\
          FindMaxFlow_OS.F90\
          FirstAllocation_OS.F90\
          fit_OS.F90\
          fitgamma_OS.F90\
          FluxWeightedConcentrationInitialize_OS.F90\
          FluxWeightedConcentrationWrite_OS.F90\
          FormatForNameList_OS.F90\
          FxTopeGlobal_OS.F90\
          FxTopeLocal_OS.F90\
          gamma_co2_OS.F90\
          gamma_OS.F90\
          gamma_init_co2_OS.F90\
          gamma_init_OS.F90\
          gamma_local_OS.F90\
          gascoeffCylinder_OS.F90\
          gasdiff_OS.F90\
          gases_OS.F90\
          gases_init_co2_OS.F90\
          gases_init_OS.F90\
          GasInjection_OS.F90\
          GetMineralNumber_OS.F90\
          GasPartialPressure_OS.F90\
          GasPartialPressure_Init_OS.F90\
          GetPrimarySpeciesNumber_OS.F90\
          GhostCells_OS.F90\
          GIMRTCrunchPETScTolerances_OS.F90\
          GlobalArrayAllocation_OS.F90\
          GlobalDensity_OS.F90\
          graphics3d_OS.F90\
          GraphicsKaleidagraph_OS.F90\
          GraphicsTecplot_OS.F90\
          GraphicsVisit_OS.F90\
          harmonic_OS.F90\
          InitializeCalciteStoichiometry_OS.F90\
          jac_exchange_OS.F90\
          jac_exchange_local_OS.F90\
          jac_local_OS.F90\
          jacexchange_OS.F90\
          jacexchange_init_OS.F90\
          jacgas_OS.F90\
          jacgas_local_OS.F90\
          jacminTope_OS.F90\
          jacobian_OS.F90\
          jacobian_init_OS.F90\
          jacobian_plus_OS.F90\
          jacpotential_OS.F90\
          JacPotentialLocal_OS.F90\
          jacrkin_OS.F90\
          jacsurf_OS.F90\
          jacsurf_init_OS.F90\
          jacsurf_local_OS.F90\
          keqcalc2_OS.F90\
          keqcalc2_init_co2_OS.F90\
          keqcalc2_init_OS.F90\
          keqcalcGasOnly_OS.F90\
          lubksb90_OS.F90\
          ludcmp90_OS.F90\
          majuscules_OS.F90\
          mindecay_OS.F90\
          mineralfind_OS.F90\
          mineral_update_OS.F90\
          modread_OS.F90\
          ModScan_OS.F90\
          movie_OS.F90\
          newfile_OS.F90\
          nrerror_OS.F90\
          NviewInit_OS.F90\
          NviewOutput_OS.F90\
          oldcon_OS.F90\
          oldcongas_OS.F90\
          oldkd_OS.F90\
          oldsurf_OS.F90\
          oldsurface_OS.F90\
          os3d_newton_OS.F90\
          PauseFor_OS.F90\
          PestExchange_OS.F90\
          PestSurface_OS.F90\
          PestScaleOutput_OS.F90\
          porcalc_OS.F90\
          porperm_OS.F90\
          Pressure_OS.F90\
          PrimarySpeciesCheck_OS.F90\
          ratecheck_OS.F90\
          reactionTope_OS.F90\
          reactkin_OS.F90\
          read98_OS.F90\
          read_AqueousFluxSeries_OS.F90\
          read_bound_OS.F90\
          read_burialfile_OS.F90\
          read_CatabolicPath_OS.F90\
          read_concentration_OS.F90\
          read_condition_OS.F90\
          read_constantflow_OS.F90\
          read_constantgasflow_OS.F90\
          read_ConstantTortuosity_OS.F90\
          read_coordinates_OS.F90\
          read_dbs_OS.F90\
          read_decay_OS.F90\
          read_diffusion_OS.F90\
          read_dispersion_OS.F90\
          read_equil_OS.F90\
          read_erosion_OS.F90\
          read_exchange_OS.F90\
          readFileName_OS.F90\
          read_flowfile_OS.F90\
          read_FluxWeightedConcentration_OS.F90\
          read_gasdiffusion_OS.F90\
          read_gasflowfile_OS.F90\
          read_gaspump_OS.F90\
          read_graphics_OS.F90\
          read_gravity_OS.F90\
          read_het_OS.F90\
          read_infiltration_OS.F90\
          read_integer_OS.F90\
          read_ionexchangeBS_OS.F90\
          read_ionexchangeMIN_OS.F90\
          read_Isotopes_OS.F90\
          read_Kd_OS.F90\
          read_kinetics_Bio_OS.F90\
          read_logical_OS.F90\
          read_master_OS.F90\
          read_mineral_OS.F90\
          read_minkin_OS.F90\
          read_MODFLOWfile_OS.F90\
          read_multpar_OS.F90\
          read_multstring_OS.F90\
          read_nuft_OS.F90\
          read_par_OS.F90\
          read_permfile_OS.F90\
          read_permx_OS.F90\
          read_permy_OS.F90\
          read_permz_OS.F90\
          read_pH_OS.F90\
          read_porosity_OS.F90\
          read_pressureAlternative_OS.F90\
          read_pump_OS.F90\
          read_restart_OS.F90\
          read_series_OS.F90\
          read_snapshot_OS.F90\
          read_SolidDensity_OS.F90\
          read_speciesdiffusion_OS.F90\
          read_steady_OS.F90\
          read_string_OS.F90\
          read_surface_OS.F90\
          read_surfacecomplex_OS.F90\
          read_temp_OS.F90\
          read_temperature_OS.F90\
          read_title_OS.F90\
          read_toperatio_OS.F90\
          read_tortuosityfile_OS.F90\
          read_TortuosityByZone_OS.F90\
          readblock_OS.F90\
          readbreak_OS.F90\
          readCaseSensitive_OS.F90\
          readCaseSensitivePar_OS.F90\
          ReadFileNameOnly_OS.F90\
          ReadFlowField_OS.F90\
          readModFlowParameters_OS.F90\
          readModFlowStress_OS.F90\
          readRecharge_OS.F90\
          ReadSaturation_OS.F90\
          readSingleString_OS.F90\
          readtype1_OS.F90\
          readtype2_OS.F90\
          readtype3_OS.F90\
          readtypescan1_OS.F90\
          reallocate_OS.F90\
          restart_OS.F90\
          rocalc_OS.F90\
          satcalc_OS.F90\
          solbt90_OS.F90\
          SolveDiffuse_OS.F90\
          SolveDiffuseSpherical_OS.F90\
          SolveGasDiffuse_OS.F90\
          speciation_OS.F90\
          species_OS.F90\
          species_init_OS.F90\
          SpeciesLocal_OS.F90\
          squeeze_OS.F90\
          sschaine_OS.F90\
          sschaine_hyph_OS.F90\
          StartTope_OS.F90\
          SteadyState_OS.F90\
          stringlen_OS.F90\
          stringtype_OS.F90\
          SurfaceComplex_OS.F90\
          surf_init_OS.F90\
          SurfaceCharge_OS.F90\
          SurfaceCharge_init_OS.F90\
          SurfaceConcentration_OS.F90\
          SurfLocal_OS.F90\
          swap_OS.F90\
          timestep_OS.F90\
          tot_ex_OS.F90\
          totconc_OS.F90\
          totconc_init_OS.F90\
          totconc_plus_OS.F90\
          totexchange_OS.F90\
          totexchange_init_OS.F90\
          totexchange_local_OS.F90\
          totgas_OS.F90\
          totgas_init_OS.F90\
          totsurf_OS.F90\
          totsurf_init_OS.F90\
          totsurf_local_OS.F90\
          tridag_ser_OS.F90\
          tvd_OS.F90\
          tvdNuft_OS.F90\
          units_concentration_OS.F90\
          units_distance_OS.F90\
          units_time_OS.F90\
          units_timeOutput_OS.F90\
          UpdateExchanger_OS.F90\
          velocalc_OS.F90\
          WaterReacted_OS.F90\
          WaterReactedNodeByNode_OS.F90\
          xmass_OS.F90\
          xmassNodeByNode_OS.F90\
          xtoolInit_OS.F90\
          xtoolOutput_OS.F90

OBJSF  =  crunchtype_OS.o\
          params_OS.o\
          strings_OS.o\
          io_OS.o\
          concentration_OS.o\
          mineral_OS.o\
          transport_OS.o\
          medium_OS.o\
          modflowModule_OS.o\
          ReadFlow_OS.o\
          RunTime_OS.o\
          solver_OS.o\
          temperature_OS.o\
          flow_OS.o\
          crunch_interface_OS.o\
          CrunchFunctions_OS.o\
          isotope_OS.o\
          NanoCrystal_OS.o\
          CrunchTopeDriver_OS.o\
          CrunchTope_OS.o\
          AffinityNumerical_OS.o\
          AllocateOS3D_OS.o\
          AllocateGIMRT_OS.o\
          AllocateALL_OS.o\
          AllocateGasesGimrt_OS.o\
          AllocateGasesOS3D_OS.o\
          AqueousFluxInitialize_OS.o\
          AqueousFluxWrite_OS.o\
          AqueousToBulkConvert_OS.o\
          AssembleLocal_OS.o\
          AssembleGlobal_OS.o\
          AverageRo_OS.o\
          bd_diffuse_OS.o\
          bdcalc_OS.o\
          bdexchange_OS.o\
          bdgas_OS.o\
          bdrecalc_OS.o\
          bdsurf_OS.o\
          breakfind_OS.o\
          BreakFindPlusCount_OS.o\
          BreakthroughInitialize_OS.o\
          BreakthroughWrite_OS.o\
          CalciteBulkStoichiometry_OS.o\
          CalciteStoichiometry_OS.o\
          CalciteStoichiometryBoundary_OS.o\
          CalculateDHAD_OS.o\
          CalculateTortuosity_OS.o\
          coeff_OS.o\
          coeff_D_OS.o\
          coeffCylinder_OS.o\
          coeffCylinder_D_OS.o\
          coeffCylinderNUFT_OS.o\
          coeffDiffuse_OS.o\
          coeffNuft_OS.o\
          coeffSphericalNew_OS.o\
          coeffSphericalNew_d_OS.o\
          convan_OS.o\
          CourantStep_OS.o\
          CourantStepAlt_OS.o\
          CPUdefinition_OS.o\
          CrunchPETScFinalizeSolver_OS.o\
          CrunchPETScInitializeChemistry_OS.o\
          CrunchPETScInitializeDiffusion_OS.o\
          CrunchPETScInitializePressure_OS.o\
          CrunchPETScTolerances_OS.o\
          database_OS.o\
          decay_OS.o\
          decbt90_OS.o\
          density_OS.o\
          dispersivity_OS.o\
          duan_OS.o\
          equilib_co2_OS.o\
          erosion_OS.o\
          ex_activity_OS.o\
          exactivity_init_OS.o\
          exchange_OS.o\
          exchange_init_OS.o\
          ExchangeConcentration_OS.o\
          find_condition_OS.o\
          find_firststring_OS.o\
          find_string_OS.o\
          FindMaxFlow_OS.o\
          FirstAllocation_OS.o\
          fit_OS.o\
          fitgamma_OS.o\
          FluxWeightedConcentrationInitialize_OS.o\
          FluxWeightedConcentrationWrite_OS.o\
          FormatForNameList_OS.o\
          FxTopeGlobal_OS.o\
          FxTopeLocal_OS.o\
          gamma_co2_OS.o\
          gamma_OS.o\
          gamma_init_co2_OS.o\
          gamma_init_OS.o\
          gamma_local_OS.o\
          gascoeffCylinder_OS.o\
          gasdiff_OS.o\
          gases_OS.o\
          gases_init_co2_OS.o\
          gases_init_OS.o\
          GasInjection_OS.o\
          GetMineralNumber_OS.o\
          GasPartialPressure_OS.o\
          GasPartialPressure_Init_OS.o\
          GetPrimarySpeciesNumber_OS.o\
          GhostCells_OS.o\
          GIMRTCrunchPETScTolerances_OS.o\
          GlobalArrayAllocation_OS.o\
          GlobalDensity_OS.o\
          graphics3d_OS.o\
          GraphicsKaleidagraph_OS.o\
          GraphicsTecplot_OS.o\
          GraphicsVisit_OS.o\
          harmonic_OS.o\
          InitializeCalciteStoichiometry_OS.o\
          jac_exchange_OS.o\
          jac_exchange_local_OS.o\
          jac_local_OS.o\
          jacexchange_OS.o\
          jacexchange_init_OS.o\
          jacgas_OS.o\
          jacgas_local_OS.o\
          jacminTope_OS.o\
          jacobian_OS.o\
          jacobian_init_OS.o\
          jacobian_plus_OS.o\
          jacpotential_OS.o\
          JacPotentialLocal_OS.o\
          jacrkin_OS.o\
          jacsurf_OS.o\
          jacsurf_init_OS.o\
          jacsurf_local_OS.o\
          keqcalc2_OS.o\
          keqcalc2_init_co2_OS.o\
          keqcalc2_init_OS.o\
          keqcalcGasOnly_OS.o\
          lubksb90_OS.o\
          ludcmp90_OS.o\
          majuscules_OS.o\
          mindecay_OS.o\
          mineralfind_OS.o\
          mineral_update_OS.o\
          modread_OS.o\
          ModScan_OS.o\
          movie_OS.o\
          newfile_OS.o\
          nrerror_OS.o\
          NviewInit_OS.o\
          NviewOutput_OS.o\
          oldcon_OS.o\
          oldcongas_OS.o\
          oldkd_OS.o\
          oldsurf_OS.o\
          oldsurface_OS.o\
          os3d_newton_OS.o\
          PauseFor_OS.o\
          PestExchange_OS.o\
          PestSurface_OS.o\
          PestScaleOutput_OS.o\
          porcalc_OS.o\
          porperm_OS.o\
          Pressure_OS.o\
          PrimarySpeciesCheck_OS.o\
          ratecheck_OS.o\
          reactionTope_OS.o\
          reactkin_OS.o\
          read98_OS.o\
          read_AqueousFluxSeries_OS.o\
          read_bound_OS.o\
          read_burialfile_OS.o\
          read_CatabolicPath_OS.o\
          read_concentration_OS.o\
          read_condition_OS.o\
          read_ConstantTortuosity_OS.o\
          read_constantflow_OS.o\
          read_constantgasflow_OS.o\
          read_coordinates_OS.o\
          read_dbs_OS.o\
          read_decay_OS.o\
          read_diffusion_OS.o\
          read_dispersion_OS.o\
          read_equil_OS.o\
          read_erosion_OS.o\
          read_exchange_OS.o\
          readFileName_OS.o\
          read_flowfile_OS.o\
          read_FluxWeightedConcentration_OS.o\
          read_gasdiffusion_OS.o\
          read_gasflowfile_OS.o\
          read_gaspump_OS.o\
          read_graphics_OS.o\
          read_gravity_OS.o\
          read_het_OS.o\
          read_infiltration_OS.o\
          read_integer_OS.o\
          read_ionexchangeBS_OS.o\
          read_ionexchangeMIN_OS.o\
          read_Isotopes_OS.o\
          read_Kd_OS.o\
          read_kinetics_Bio_OS.o\
          read_logical_OS.o\
          read_master_OS.o\
          read_mineral_OS.o\
          read_minkin_OS.o\
          read_MODFLOWfile_OS.o\
          read_multpar_OS.o\
          read_multstring_OS.o\
          read_nuft_OS.o\
          read_par_OS.o\
          read_permfile_OS.o\
          read_permx_OS.o\
          read_permy_OS.o\
          read_permz_OS.o\
          read_pH_OS.o\
          read_porosity_OS.o\
          read_pressureAlternative_OS.o\
          read_pump_OS.o\
          read_restart_OS.o\
          read_series_OS.o\
          read_snapshot_OS.o\
          read_SolidDensity_OS.o\
          read_speciesdiffusion_OS.o\
          read_steady_OS.o\
          read_string_OS.o\
          read_surface_OS.o\
          read_surfacecomplex_OS.o\
          read_temp_OS.o\
          read_temperature_OS.o\
          read_title_OS.o\
          read_toperatio_OS.o\
          read_tortuosityfile_OS.o\
          read_TortuosityByZone_OS.o\
          readblock_OS.o\
          readbreak_OS.o\
          readCaseSensitive_OS.o\
          readCaseSensitivePar_OS.o\
          ReadFileNameOnly_OS.o\
          ReadFlowField_OS.o\
          readModFlowParameters_OS.o\
          readModFlowStress_OS.o\
          readRecharge_OS.o\
          ReadSaturation_OS.o\
          readSingleString_OS.o\
          readtype1_OS.o\
          readtype2_OS.o\
          readtype3_OS.o\
          readtypescan1_OS.o\
          reallocate_OS.o\
          restart_OS.o\
          rocalc_OS.o\
          satcalc_OS.o\
          solbt90_OS.o\
          SolveDiffuse_OS.o\
          SolveDiffuseSpherical_OS.o\
          SolveGasDiffuse_OS.o\
          speciation_OS.o\
          species_OS.o\
          species_init_OS.o\
          SpeciesLocal_OS.o\
          squeeze_OS.o\
          sschaine_OS.o\
          sschaine_hyph_OS.o\
          StartTope_OS.o\
          SteadyState_OS.o\
          stringlen_OS.o\
          stringtype_OS.o\
          SurfaceComplex_OS.o\
          surf_init_OS.o\
          SurfaceCharge_OS.o\
          SurfaceCharge_init_OS.o\
          SurfaceConcentration_OS.o\
          SurfLocal_OS.o\
          swap_OS.o\
          timestep_OS.o\
          tot_ex_OS.o\
          totconc_OS.o\
          totconc_init_OS.o\
          totconc_plus_OS.o\
          totexchange_OS.o\
          totexchange_init_OS.o\
          totexchange_local_OS.o\
          totgas_OS.o\
          totgas_init_OS.o\
          totsurf_OS.o\
          totsurf_init_OS.o\
          totsurf_local_OS.o\
          tridag_ser_OS.o\
          tvd_OS.o\
          tvdNuft_OS.o\
          units_concentration_OS.o\
          units_distance_OS.o\
          units_time_OS.o\
          units_timeOutput_OS.o\
          UpdateExchanger_OS.o\
          velocalc_OS.o\
          WaterReacted_OS.o\
          WaterReactedNodeByNode_OS.o\
          xmass_OS.o\
          xmassNodeByNode_OS.o\
          xtoolInit_OS.o\
          xtoolOutput_OS.o

LOCDIR   = ${CrunchTope_Dir}

## For PETSc 3.0X
##include ${PETSC_DIR}/conf/base
## For PETSc 3.2X
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

CrunchMain : ${OBJSF} chkopts 
	-${FLINKER} -o CrunchTope ${OBJSF} ${PETSC_FORTRAN_LIB} ${PETSC_LIB} ${FFLAGS}

